import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  Background: {
    flex: 1,
    resizeMode: 'cover',
    justifyContent: 'center',
    backgroundColor: '#FFFAFA',
    alignItems: 'center',
    height: '100%',
  },
  Header: {
    borderColor: 'black',
    borderWidth: 0.1,
    top: '-10%',
    borderTopColor: '#FFFFFF',
    // backgroundColor: '#FFFFFF',
    right: '20%',
    shadowColor: 'black',
    shadowOffset: {width: 0, height: 1},
    shadowRadius: 2,
    shadowOpacity: 0.05,
    width: '100%',
    left: '0.2%',
    padding: '0.5%',
    alignItems: 'center',
    elevation: 1,
    height: '70%',
    paddingTop: 20,
    backgroundColor: 'black',
  },
  input: {
    marginTop: '05%',
    backgroundColor: '#fff',
    flex: 2,
    width: '90%',
    flexDirection: 'row',
    alignItems: 'center',
    //left: 0,
    // flexDirection: 'row',
    // justifyContent: 'center',
    // alignItems: 'center',
    // backgroundColor: 'black',
    // width: '90%',
    // borderColor: 'black',
    // borderWidth: 0,
    // // eslint-disable-next-line no-dupe-keys
    // backgroundColor: 'black',
    // shadowColor: 'black',
    // shadowOffset: {width: 0, height: 1},
    // shadowRadius: 2,
    // shadowOpacity: 0.05,
    // borderRadius: 5,
    // elevation: 2,
    // flex: 2,
    // height: '-100%',
  },
  item: {
    marginTop: 24,
    padding: 30,
  },
  upper: {
    width: '100%',
    height: '35%',
    backgroundColor: 'yellow',
    flex: 1,
    alignItems: 'center',
    top: 10,
  },
  secondupper: {
    top: 0,
    width: '100%',
    height: '30%',
    flex: 2,
    backgroundColor: 'pink',
  },
  Top4: {top: '05%', height: '20%'},
  buttonView: {flexDirection: 'row', width: '80%'},
  middleText: {fontSize: 50, marginLeft: '10%', top: '01%'},
  scrollView: {width: '100%', height: '50%', top: 40},
  // eslint-disable-next-line no-dupe-keys
  scroll: {marginTop: 60, marginTop: '-5%', marginBottom: '05%'},
  map: {
    width: 'auto',
    height: 120,
    marginTop: '5%',
    alignItems: 'center',
  },
  Top10: {
    top: '10%',
  },
  shopping: {
    marginLeft: '10%',
    top: '10%',
  },
  backgroundBox: {
    justifyContent: 'center',
    backgroundColor: '#fff',
    width: '100%',
    flex:5,
    alignItems: 'center',
  },

  searchBox: {
    width: '90%',
    justifyContent: 'center',
    alignSelf: 'center',
    backgroundColor: 'black',
    top:10
  },
});
export default styles;
