import {StyleSheet} from 'react-native';
const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
  },
  image: {
    flex: 1,
    resizeMode: 'cover',
    justifyContent: 'center',
  },
  text: {
    color: 'white',
    fontSize: 42,
    fontWeight: 'bold',
    textAlign: 'center',
    backgroundColor: '#000000a0',
  },
  demo: {
    backgroundColor: '#FFFAFA',
    width: '90%',
    height: 500,
    borderRadius: 10,
    left: '35%',
    marginLeft: '-30%',
    alignItems: 'center',
  },

  signuppage: {
    borderColor: 'black',
    borderWidth: 0.1,
    height: '20%',
    backgroundColor: '#FFFFFF',
    right: '20%',
    shadowColor: 'black',
    shadowOffset: {width: 0, height: 1},
    shadowRadius: 2,
    shadowOpacity: 0.05,
    elevation: 2,
    width: '100%',
    left: '0.2%',
    marginTop: 0.7,
    padding: '0.5%',
    alignItems: 'center',
  },
  button: {
    borderColor: 'black',
    borderWidth: 0,
    backgroundColor: '#FFFFFF',
    shadowColor: 'black',
    shadowOffset: {width: 0, height: 1},
    shadowRadius: 2,
    shadowOpacity: 0.05,
    elevation: 2,
    height: '70%',
    alignItems: 'center',
  },
  searchSection: {
    marginTop: '15%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '90%',
    borderColor: 'black',
    borderWidth: 0,
    backgroundColor: '#FFFFFF',
    shadowColor: 'black',
    shadowOffset: {width: 0, height: 1},
    shadowRadius: 2,
    shadowOpacity: 0.05,
    elevation: 2,
  },
  searchSection1: {
    marginTop: '05%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '90%',
    borderColor: 'black',
    borderWidth: 0,
    backgroundColor: '#FFFFFF',
    shadowColor: 'black',
    shadowOffset: {width: 0, height: 1},
    shadowRadius: 2,
    shadowOpacity: 0.05,
    elevation: 2,
  },
  Textcolor: {color: '#8898AA'},
  row: {flexDirection: 'row'},
  IconText: {color: 'blue', marginLeft: 10, fontSize: 18},
  margin20: {marginLeft: 20},
  margin10: {marginLeft: 10},
  Textsing: {color: '#8898AA', top: 20},
  padding5: {padding: 5},
  checkbox: {flexDirection: 'row', top: '07%', marginRight: '27%'},
  checkBox: {borderWidth: 3},
  Top3: {top: '03%'},
  colorTop: {color: '#663399', top: '03%'},
  Buttocomponet: {width: '70%', top: '10%'},
});
export default styles;
